//
//  LMConstants.h
//  iOS-Deep-Linking-SDK
//  Created by han on 6/10/15.
//  Copyright (c) 2015 LM han. All rights reserved.
//

#import <Foundation/Foundation.h>

extern NSString * const LINKEDME_REQUEST_KEY_LKME_IDENTITY;
extern NSString * const LINKEDME_REQUEST_KEY_DEVELOPER_IDENTITY;
extern NSString * const LINKEDME_REQUEST_KEY_ACTION;
extern NSString * const LINKEDME_REQUEST_KEY_BUCKET;
extern NSString * const LINKEDME_REQUEST_KEY_AMOUNT;
extern NSString * const LINKEDME_REQUEST_KEY_LENGTH;
extern NSString * const LINKEDME_REQUEST_KEY_DIRECTION;
extern NSString * const LINKEDME_REQUEST_KEY_STARTING_TRANSACTION_ID;
extern NSString * const LINKEDME_REQUEST_KEY_REFERRAL_USAGE_TYPE;
extern NSString * const LINKEDME_REQUEST_KEY_REFERRAL_REWARD_LOCATION;
extern NSString * const LINKEDME_REQUEST_KEY_REFERRAL_TYPE;
extern NSString * const LINKEDME_REQUEST_KEY_REFERRAL_CREATION_SOURCE;
extern NSString * const LINKEDME_REQUEST_KEY_REFERRAL_PREFIX;
extern NSString * const LINKEDME_REQUEST_KEY_REFERRAL_EXPIRATION;
extern NSString * const LINKEDME_REQUEST_KEY_REFERRAL_CODE;
extern NSString * const LINKEDME_REQUEST_KEY_URL_DATA;
extern NSString * const LINKEDME_REQUEST_KEY_APP_LIST;
extern NSString * const LINKEDME_REQUEST_KEY_HARDWARE_ID;
extern NSString * const LINKEDME_REQUEST_KEY_IS_HARDWARE_ID_REAL;
extern NSString * const LINKEDME_REQUEST_KEY_DEBUG;
extern NSString * const LINKEDME_REQUEST_KEY_URI_SCHEME;
extern NSString * const LINKEDME_REQUEST_KEY_LINK_IDENTIFIER;
extern NSString * const LINKEDME_REQUEST_KEY_MODEL;
extern NSString * const LINKEDME_REQUEST_KEY_DEVICE_NAME;
extern NSString * const LINKEDME_REQUEST_KEY_IS_SIMULATOR;
extern NSString * const LINKEDME_REQUEST_KEY_LOG;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_SET_IDENTITY;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_LOGOUT;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_USER_COMPLETED_ACTION;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_LOAD_ACTIONS;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_LOAD_REWARDS;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_REDEEM_REWARDS;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_CREDIT_HISTORY;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_GET_PROMO_CODE;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_GET_REFERRAL_CODE;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_VALIDATE_PROMO_CODE;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_VALIDATE_REFERRAL_CODE;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_APPLY_PROMO_CODE;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_APPLY_REFERRAL_CODE;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_GET_SHORT_URL;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_CLOSE;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_GET_APP_LIST;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_UPDATE_APP_LIST;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_OPEN;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_BUTTON;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_INSTALL;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_CONNECT_DEBUG;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_DISCONNECT_DEBUG;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_LOG;
extern NSString * const LINKEDME_REQUEST_ENDPOINT_REGISTER_VIEW;
extern NSString * const LINKEDME_IS_REFERABLE;



extern NSString * const LINKEDME_RESPONSE_KEY_INSTALL_PARAMS;
extern NSString * const LINKEDME_RESPONSE_KEY_ACTION_COUNT_TOTAL;
extern NSString * const LINKEDME_RESPONSE_KEY_ACTION_COUNT_UNIQUE;
extern NSString * const LINKEDME_RESPONSE_KEY_REFERREE;
extern NSString * const LINKEDME_RESPONSE_KEY_REFERRAL_CODE;
extern NSString * const LINKEDME_RESPONSE_KEY_PROMO_CODE;
extern NSString * const LINKEDME_RESPONSE_KEY_URL;
extern NSString * const LINKEDME_RESPONSE_KEY_SPOTLIGHT_IDENTIFIER;
extern NSString * const LINKEDME_RESPONSE_KEY_POTENTIAL_APPS;
//extern NSString * const LINKEDME_RESPONSE_KEY_DEVICE_FINGERPRINT_ID;
//extern NSString * const LINKEDME_RESPONSE_KEY_SESSION_DATA;
extern NSString * const LINKEDME_RESPONSE_KEY_CLICKED_BRANCH_LINK;

extern NSString * const LINKEDME_LINK_DATA_KEY_OG_TITLE;
extern NSString * const LINKEDME_LINK_DATA_KEY_OG_DESCRIPTION;
extern NSString * const LINKEDME_LINK_DATA_KEY_OG_IMAGE_URL;
extern NSString * const LINKEDME_LINK_DATA_KEY_TITLE;
extern NSString * const LINKEDME_LINK_DATA_KEY_DESCRIPTION;
extern NSString * const LINKEDME_LINK_DATA_KEY_PUBLICLY_INDEXABLE;
extern NSString * const LINKEDME_LINK_DATA_KEY_TYPE;
extern NSString * const LINKEDME_LINK_DATA_KEY_THUMBNAIL_URL;
extern NSString * const LINKEDME_LINK_DATA_KEY_KEYWORDS;
extern NSString * const LINKEDME_LINK_DATA_KEY_CANONICAL_IDENTIFIER;
extern NSString * const LINKEDME_LINK_DATA_KEY_CANONICAL_URL;
extern NSString * const LINKEDME_LINK_DATA_KEY_CONTENT_EXPIRATION_DATE;
extern NSString * const LINKEDME_LINK_DATA_KEY_CONTENT_TYPE;
extern NSString * const LINKEDME_LINK_DATA_KEY_EMAIL_SUBJECT;
extern NSString * const LINKEDME_LINK_DATA_KEY_METADATA;
extern NSString * const LINKEDME_LINK_DATA_KEY_CONTROL;
extern NSString * const LINKEDME_SPOTLIGHT_PREFIX;




#pragma mark ****************
extern NSString * const LINKEDME_REQUEST_KEY_URL_METADATA;


extern NSString * const LKME_REQUEST_KEY_EXTERNAL_INTENT_URI;
extern NSString * const LINKEDME_REQUEST_KEY_DEVICE_FINGERPRINT_ID;
extern NSString * const LINKEDME_REQUEST_KEY_BUNDLE_ID;
extern NSString * const LINKEDME_REQUEST_KEY_DEVICE_ID;
extern NSString * const LINKEDME_REQUEST_KEY_DEVICE_TYPE;
extern NSString * const LINKEDME_REQUEST_KEY_DEVICE_BRAND;
extern NSString * const LINKEDME_REQUEST_KEY_DEVICE_MODEL;
extern NSString * const LINKEDME_REQUEST_KEY_HAS_BLUETOOTH;
extern NSString * const LINKEDME_REQUEST_KEY_HAS_NFC;
extern NSString * const LINKEDME_REQUEST_KEY_HAS_SIM;
extern NSString * const LINKEDME_REQUEST_KEY_OS;
extern NSString * const LINKEDME_REQUEST_KEY_OS_VERSION;
extern NSString * const LKME_REQUEST_KEY_SCREEN_DPI;
extern NSString * const LINKEDME_REQUEST_KEY_SCREEN_HEIGHT;
extern NSString * const LINKEDME_REQUEST_KEY_SCREEN_WIDTH;
extern NSString * const LINKEDME_REQUEST_KEY_IS_WIFT;
extern NSString * const LINKEDME_REQUEST_KEY_IS_REFERRABLE;
extern NSString * const LINKEDME_REQUEST_KEY_IS_DEBUG;
extern NSString * const LINKEDME_REQUEST_KEY_CARRIER;
extern NSString * const LINKEDME_REQUEST_KEY_APP_VERSION;
extern NSString * const LINKEDME_REQUEST_KEY_UNIVERSAL_LINK_URL;
extern NSString * const LINKEDME_REQUEST_KEY_UPDATE;
extern NSString * const LINKEDME_REQUEST_KEY_AD_TRACKING_ENABLED;
extern NSString * const LINKEDME_REQUEST_KEY_TEAM_ID;
extern NSString * const LINKEDME_REQUEST_KEY_SPOTLIGHT_IDENTIFIER;
extern NSString * const LINKEDME_REQUEST_KEY_SESSION_ID;




extern NSString * const LINKEDME_RESPONSE_KEY_DEVELOPER_IDENTITY;
extern NSString * const LINKEDME_RESPONSE_KEY_DEVICE_FINGERPRINT_ID;
extern NSString * const LINKEDME_RESPONSE_KEY_USER_URL;
extern NSString * const LINKEDME_RESPONSE_KEY_SESSION_ID;
extern NSString * const LINKEDME_RESPONSE_KEY_SESSION_DATA;
extern NSString * const LINKEDME_RESPONSE_KEY_CLICKED_LINKEDME_LINK;
extern NSString * const LKME_RESPONSE_KEY_URL;
extern NSString * const LINKEDME_RESPONSE_KEY_IDENTITY_ID;
extern NSString * const LINKEDME_RESPONSE_KEY_IS_FIRST_SESSION;


extern NSString * const LINKEDME_REQUEST_KEY_URL_SOURCE;
extern NSString * const LINKEDME_REQUEST_KEY_URL_TAGS;
extern NSString * const LINKEDME_REQUEST_KEY_URL_LINK_TYPE;
extern NSString * const LINKEDME_REQUEST_KEY_URL_ALIAS;
extern NSString * const LINKEDME_REQUEST_KEY_URL_CHANNEL;
extern NSString * const LINKEDME_REQUEST_KEY_URL_FEATURE;
extern NSString * const LINKEDME_REQUEST_KEY_URL_STAGE;
extern NSString * const LINKEDME_REQUEST_KEY_URL_DURATION;
extern NSString * const LKME_REQUEST_KEY_URL_DATA;
extern NSString * const LINKEDME_REQUEST_KEY_URL_IGNORE_UA_STRING;


extern NSString * const LINKEDME_REQUEST_KEY_BTN_ID;
extern NSString * const LINKEDME_REQUEST_KEY_PICKUP_LAT;
extern NSString * const LINKEDME_REQUEST_KEY_PICKUP_LNG;
extern NSString * const LINKEDME_REQUEST_KEY_PICKUP_LABEL;
extern NSString * const LINKEDME_REQUEST_KEY_DROPOFF_LAT;
extern NSString * const LINKEDME_REQUEST_KEY_DROPOFF_LNG;
extern NSString * const LINKEDME_REQUEST_KEY_DROPOFF_LABEL;

extern NSString * const PARAMS_ANDROID_LINK;
extern NSString * const PARAMS_IOS_LINK;










